### ISSUE TITLE
Add optional printing of current program state (e.g. working top level folder) to `DataShuttle.__init__()`

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#117]
Add a toggleable 'print welcome message' to datashuttle init. As the program develops it will be useful to print the current state of the program when it is loaded. However, the CLI works by first initialising a `DataShuttle` project and then calling the relevant functions. We don't really want to print the entire state every time a CLI argument is called (e.g. `show_local_path`). However, for some CLI arguments this will be useful (e.g. `make_config_file`). The easiest way to deal with this is have a optional argument on `DataShutte` init that prints or does not print the message (default `True`). We can set this to `False` on the CLI calls we want to hide this welcome message.

----

At present the current working 'top level folder' (e.g. `rawdata`, `derivatives` etc. ) is planned to be set in a persistent state across sessions, and changed with the method `set_top_level_folder()`.

This is probably the cleanest way to do it, but the only pit-fall is it may be easy to forget the current working top level name, and do things like make folders / transfer folders from the wrong top-level folder. The best protect against this is to print the current top level folder frequency e.g. on program load. This can be done as described above

**Comment by niksirbi** [comment]
Yeah, printing the current state on program load is a good one. Another thing to add to the reported "state" could be the names of the existing projects. I often forget how I named the project and that argument is needed for every command.
The TUI will also help with these issues, since we can always display the state info somewhere on it.
