### ISSUE TITLE
[CLI] Merge similar CLI commands

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/datashuttle#125]
## Problem
Currently `datashuttle` has a growing list of  functions/programs that can be run from the command line, namely:
```bash
    update-config (update_config)
    setup-ssh-connection-to-remote-server (setup_ssh_connection_to_remote_server)
    make-sub-folders (make_sub_folders)
    upload-data (upload_data)
    upload-all (upload_all)
    download-data (download_data)
    download-all (download_all)
    upload-project-folder-or-file (upload_project_folder_or_file)
    download-project-folder-or-file (download_project_folder_or_file)
    show-local-path (show_local_path)
    show-datashuttle-path (show_datashuttle_path)
    show-config-path (show_config_path)
    show-remote-path (show_remote_path)
    show-configs (show_configs)
    show-logging-path (show_logging_path)
    show-local-tree (show_local_tree)
    check-name-formatting (check_name_formatting)
    supply-config-file (supply_config_file)
```

## Proposed solution
From the user's perspective, it would be simpler to merge some of those into fewer commands.
For example, all the `show-*` commands could be replaced via a single command that takes "what to show" as an argument.
A toy example:
```bash
$ datashuttle show --local-path --remote-path --configs
```
Alternatively, to print all "show" outputs
```bash
$ datashuttle show --all
```

## Caveats
- I don't know how hard it would be to change this, given the current architecture of `datashuttle`. Might be not worth doing if it's too much of a hustle. On the other hand, if it's easy, we could extend this "simplification" to more commands (e.g. group all `download-*` and all `upload-*` commands. 
- The ease of use of the CLI might become irrelevant if a TUI ends up as the main way users interact with it.

**Comment by JoeZiminski** [comment]
This is very nice, I think it would be okay to implement. The existing functions could be made private and one master function can call them based on the items in a list (e.g. `project.show(["local_path", "remote_path"])`, this would be easy to wrap in the suggested CLI command.
