### ISSUE TITLE
[TUI] General TUI Notes

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#224]
This issue describes small notes and things to implement that are generated from PRs but that it makes more sense to tackle later.

Directory Tree
- [x] double click also opens and close the folder, consider using right-click or a hold-button + click.
- [ ] delete directories through the directory tree
- [x] update the directory tree either periodically or whenever it is clicked in order to display changes that have been made in the underlying filesystem (e.g. if deleting a file through the system file browser) (see https://github.com/Textualize/textual/issues/3574)
- [x] maybe only show the root folder name at the top and provide an easy way to get the full path (e.g. right-click menu)

**Comment by b-peri** [comment]
**Project Selection Screen**
- Implement lightweight script for extraction of project metadata (date created, date last edited, datatypes, n_subjects, etc.)

**Create Tab**
- “Templating” + dynamic inference of “Next” subject/session value
- Validation of sub and ses strings (with corresponding tcss properties → Change in border color when valid/invalid)
- Implement ToolTips that appear when hovering over `Input` or `DirectoryTree` widgets.
- Force tree open up to ses level!

**Settings Tab** -> For changing view settings etc.

**Comment by JoeZiminski** [comment]
Windows powershell or cmd does not work we,, `Anaconda Powershell prompt, which looks pretty much exactly the same as the WIndows Terminal ` (both look good). If the anaconda temrinal looks good cross platform we can just reccomend running in this.

**Comment by JoeZiminski** [comment]
macOS is rendering weird, this is know textual problem that does not look like a quick fix. This makes it difficult to recommend it's use on Mac.

Down the line it would be nice to package datashuttle, so use does not need to worry about installing conda at all. Under this model I believe we should be able to spin up an anaconda prompt ourselves, i.e. forcing the user to use a terminal we know will render properly. Until then though we will have to ask users to install a different terminal for best experience on macOS. If this is the case and there are no workarounds we should move to a package install as soon as possible.

**Comment by JoeZiminski** [comment]
Some misc. general TODOs
1. add persistant settings for create tab ( checkboxes), has a button or something that brings up modal window for create-tab preferences (e.g. autofill options)
2. Add type hints, some preliminary tests just to understand how textualize is testing
3. update datashuttle to have an option to return the existing projects in last-modified order so they can be displayed in this order on TUI

**Comment by JoeZiminski** [comment]
5. We need somewhere to 'setup-ssh-connection-to-central-server'.

**Comment by JoeZiminski** [comment]
- add tooltips to all relevant widgets
- refresh the directory tree on filesytem change - textual currently implementing updated filetree that keeps the currently selected node when the directorytree is updated (currently it refreshes to root)
- Figure out best how to present to the user that validation is local vs. central (SSH is very slow)
- add tests
-

**Comment by JoeZiminski** [comment]
Some TUI feedback:


Datashuttle meeting 22/11/2023

filetree for config path selection
typing in path a last resort

remove confirmation confogs screen
rename Configure Project to save

central path brought into connection method level

fix remote machine name at start of central path 

rename ‘central_host_username’ to ‘central_host’

change central host autofill 

Regex builder with buttons to input commenly used preset

Let people delete stuff with a warning

option to whitelist validation and make files anyway

datatype name lowercase

a little question mark somewhere on tags, right / left click etc.

**Comment by JoeZiminski** [comment]
Add a hold key + double click on file to append new suggested file rather than replacing.

**Comment by JoeZiminski** [comment]
Add 'Options' button on Transfer tab that contains transfer related options which are currently stored in CFG.

**Comment by JoeZiminski** [comment]
see https://textual.textualize.io/getting_started/ for terminals that textual runs on. Best option is probably to package all terminals (if possible) (or use system if works) and just launch them + run command in them from python (again, if possible).

**Comment by JoeZiminski** [comment]
https://stackoverflow.com/questions/38489755/python-script-to-type-something-in-terminal
