### ISSUE TITLE
Update PyPI description

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/datashuttle#241]
Currently it references BIDS and isn't strictly accurate. This is important because the description is prominant on the [PyPI page](https://pypi.org/project/datashuttle/).

**Comment by JoeZiminski** [comment]
Good spot, would:

```
Datashuttle automates the creation and management of standardised neuroscience projects.
```
work?

**Comment by adamltyson** [comment]
```
DataShuttle automates the creation and management of standardised neuroscience data directories.
```
Just to be explicit? @niksirbi any thoughts?

**Comment by adamltyson** [comment]
I like @niksirbi's more.

**Comment by JoeZiminski** [comment]
Nice that looks great, do we want to say 'folders' rather than 'directories' for consistentcy with the codebase? In this case, I actually think 'directories' is clearer / sounds better though.

**Comment by niksirbi** [comment]
I'd go with "folder" for consistency + target market considerations
