### ISSUE TITLE
Think about how to handle duplicate sessions (e.g. behaviour vs. ephys > behaviour)

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#25]
Often experiments are structured with long periods of behavioural training (behaviour only) interspered with ephys or other sessions that include behaviour as a contstituent part (e.g. a test session with NP recording + behaivour). How to handle the behaviour stored in this case is not clear.  Options are:

1) store behaviour data under ephys - this is nice as all session data is together. However this is a problem when looking at behaviour folder as this session will be missing, and the session number could be duplicated.
2) store ephys behaviour data under behavior . This means that behaviour folder sessions are aligned, but ephys behaviour data is not with the other ephys files, and there is some divergence e.g. 'ephys session 2 used behaviour session 32'

A possible solution is symlinking (e..g make a symlink to ephys>behav folder in behav (though might be some cross platform issues https://unix.stackexchange.com/questions/63172/does-windows-recognize-linuxs-symbolic-links). 

This is something to discuss with researchers about preferred behavior and how they currently handle this organisation.

**Comment by adamltyson** [comment]
Hmm, this seems important. 

I'm not a huge fan of storing one type of data "under" another. Is there a way we can solve this with metadata? I.e. when you create a new session (that might be ephys session 1 but behaviour session 50) there is some metadata that associates these? This metadata could be expanded later to align recordings in time.

**Comment by JoeZiminski** [comment]
Yes I've discussed with Niko a bit too and its definately a key thing to think about. Using the meta-data is a nice idea, it would definately be cleanest to split by data type. 

I think it would be good to survey researchers about what they do at the moment / think is the best approach. The main issue of splitting up the data-type is that it can make things a bit more confusing as there is some duplication of session number. e.g. for some arbitary experimental design where there are 5 training sessinons,  a test session, then another 5 training sessions, and a second test session. You might usually split this into training data - behaviour, and ephys data. Then its easy to think 'test behaviour is in ephys tests 1, 2' rather than having to figure out 'behaviour session 6 is ephys session 1, behaviour session 12 is ephys session 2'. Obviously if you have 100 training sessions and 10 test sessions this can get quite complicated, although we could of course provide tools to make it as smooth as possible.

Overall its definatly neater, and better for project organisation to split it by data type, and many labs may already do this, but it could be something people might feel strongly about. I'll also raise an issue on the BIDS extension protocol github to see what their thoughts are on this.

**Comment by adamltyson** [comment]
> Then its easy to think 'test behaviour is in ephys tests 1, 2'

To me it's very confusing if ephys *anything* 1 doesn't actually have any ephys data.

Agree that a survey is the right approach. We may find common patterns of how people like to store/handle/analyse data.

In the end I think *any* schema is better than nothing though, so we will have to decide on something.

Another option is to focus on the API and not on the storage backend. How will people actually interact with the data? And could we offer both a data-first and an experiment-first interface?

**Comment by niksirbi** [comment]
I like the symlink approach, but as you said Joe, this will probably lead to cross-platform issues. Storing the 'link' info in a metadata file could be the fall-back solution.

I just had another __idea__ though:
Currently the data is organized as follows:

```
└── project_name/
    └── raw_data/
        ├── ephys/
        │   └── sub-001/
        │       ├── ses-001
        │       └── ses-002
        └── behav/
            └── sub-001/
                ├── ses-001
                └── ses-002
```
Instead, we could organise the data with the modality (ephys, behav, etc) level below the session level, thus:
```
└── project_name/
    └── raw_data/
        ├── sub-001/
        │   └── ses-001/
        │       ├── ephys/
        │       └── behav/
        │   └── histology/
        └── sub-002/
            └── ses-001/
                ├── behav/
                └── imaging/
            └── ses-002/
                └── behav/
            └── histology/
```
This way, the session number always increments by one no matter what experiment was done (ephys, behav, imaging). Each session subfolder includes directories only for the modalities that were actually acquired. If ephys was acquired only during a subset of a behavioral session, this should be somehow stored in metadata to handle synchronisation. Histology is an exception to this scheme, since it can only be done once per subject, so it belongs under the subject-level directory.

The added benefit of nesting the modalities under the sub/ses levels is that it directly mirrors how BIDS handles MRI data. Quote from their specification:
> Data type - A functional group of different types of data. Data files are contained in a directory named for the data type. In raw datasets, the data type directory is nested inside subject and (optionally) session directories. BIDS defines the following data types: func (task based and resting state functional MRI), dwi (diffusion weighted imaging), fmap (field inhomogeneity mapping data such as field maps), anat (structural imaging such as T1, T2, PD, and so on).....

There may be ways in which this scheme doesn't work for systems neuroscience experiments, though I cannot foresee them without getting direct feedback. I also do realise that if we go with my suggestion, the code will require lots of restructuring.

What do you think?

**Comment by JoeZiminski** [comment]
I think that is a nice approach that solves the main problem, the reasons for not originally going that route are below*, but I think those issues are less than those caused by the current implementation, for which either solution is sub-optimal. 

I posted an issue on https://github.com/INCF/neuroscience-data-structure/issues/12, please feel free to add / I am happy to make any edits. Also, for surveying researchers, how about something like the below message (happy for anyone to post it) on SWC slack (not sure what is best channel for this):

"Hi everyone, we at the neuroinformatics-unit are thinking about the best ways to standardised project folder structure as much as possible across the SWC. There have been many great initiatives to promote standardized folder structures (e.g. BIDS), but there still many cases where the appropriate structure is not clear. We wanted to know how you are structuring your project folders, in particular the different data types (e.g. ephys, behaviour, imaging etc.). e.g. do you store all behavioural types for a single session together, or split all sessions by data type? It would be great to hear back how you do this, or event create a quick example of your structure at: https://tree.nathanfriend.io/! Thanks, neuroinformatics team"

^quite rough so please feel free to edit as much as you like



--- 

Not arguing these points but just want I thought at the time:

- because the structure it mixes the data types, it is difficult for a researcher with no coding experience to select the data by datatype and transfer it, by hand. Similarly, it is difficult to find certain sessions by browsing the folder structure rather than accessing programmatically. Although datashuttle would do all of this for the user, I like the idea that the folder structure is still very convenient to manipulate by hand in a way that is natural for the researcher, just so working with their data outside datashuttle is not frustrating. That been said, maybe researchers already use this structure and copy by hand anyway.

- the BEP for ephys top level directory is ephys, and there are other BEP e.g. for intracellular electrophysiology, microscopy (https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/10-microscopy.html). This gave me a vague idea it would be better to split the folders by datatype, but I think these considerations should come second to optimal directory organisation.

**Comment by adamltyson** [comment]
> "Hi everyone, we at the neuroinformatics-unit are thinking about the best ways to standardised project folder structure as much as possible across the SWC. There have been many great initiatives to promote standardized folder structures (e.g. BIDS), but there still many cases where the appropriate structure is not clear. We wanted to know how you are structuring your project folders, in particular the different data types (e.g. ephys, behaviour, imaging etc.). e.g. do you store all behavioural types for a single session together, or split all sessions by data type? It would be great to hear back how you do this, or event create a quick example of your structure at: https://tree.nathanfriend.io/! Thanks, neuroinformatics team"

Looks good to me. I think you should post it as you're leading this effort (otherwise there will be a lot of forwarding messages to you). 

Agree with your other points above. I think I'm leaning towards the session-first approach, but as @robertoostenveld pointed out in https://github.com/INCF/neuroscience-data-structure/issues/12#issuecomment-1305769552, the most important thing is that we have *a* standard, and that we support it very well with tools/docs/training etc.

**Comment by niksirbi** [comment]
_Hey @JoeZiminski ,_ 

_In case you haven't sent the message around, below I suggest a bit of rephrasing, and have also added tree examples, to make sure it's clear what we mean. Feel free to adopt (parts of) my version, or not._

"Hi everyone, we at the neuroinformatics-unit are thinking about the best ways to standardise project folder structure as much as possible across the SWC. There have been many great initiatives to promote standardized folder structures (e.g. [BIDS](https://bids.neuroimaging.io/)), but in many cases the appropriate structure is not clear. 

We wanted to know how you are structuring your project folders, in particular when they include different data types (e.g. ephys, behaviour, imaging etc.). Do you store all data types for a single session together (resembling __option A__), or split all sessions by data type (closer to __Option B__)? 

### Option A
```bash
Project
└── mouse-01
    ├── session-01
    │   ├── ephys
    │   └── behaviour
    └── session-02
        ├── ephys
        └── behaviour
```
### Option B
```bash
Project
└── mouse-01
    ├── ephys
    │   ├── session-01
    │   └── session-02
    └── behaviour
        ├── session-01
        └── session-02
```

It would be great to hear back how you do this, or what appears as more useful/intuitive to you. The best would be to create a quick example of your project folder structure at: https://tree.nathanfriend.io/!

Thanks, the neuroinformatics team"
