### ISSUE TITLE
[TUI] Refactor TUI Code (6)

### ISSUE THREAD

**Issue by b-peri** [neuroinformatics-unit/datashuttle#262]
The TUI code is starting to become a bit bloated, and it is now becoming difficult to work on the TUI in parallel. To ameliorate these issues, we should perform a major refactoring of the TUI code into separate modules. In the General Meeting Notes issue (#184), I proposed the following re-organization:

<img width="672" alt="image" src="https://github.com/neuroinformatics-unit/datashuttle/assets/77279592/d77da148-ab79-4b5b-aefd-945cb5c7c5b2">

- `tui_app.py`: The main Textual app for the TUI (`TuiApp`), and the script that the user will call from the terminal (using textual) when they want to run the TUI.
- `project_config.py`: `ConfigsContent`, `NewProjectScreen`, and associated objects involving configuration of a new project or updating configs for a pre-existing project.
- `tui_logic.py`: TUI-specific functions and logic
- `custom_widgets.py`: Custom widgets and **multi-use** modal windows built for the TUI (e.g. `DatatypeCheckboxes` or `ErrorScreen`, but not `ShowConfigsDialog`)
- TabScreen Tabs will be subdivided into:
     - `main_tab.py`: Containing the main `TabScreen` and associated (non-tab-specific) logic
     - `create_tab.py`: Create tab and associated logic
     - `transfer_tab.py`: Transfer tab and associated logic
     - And so on...
     - **NOTE:** The configs tab will likely not require a separate script from `project_config.py` 

However, this is by no means set in stone, so please let me know if a different organization would make more sense!

**Comment by JoeZiminski** [comment]
Hey @b-peri  thank a lot for this and the other notes, looks great! Down the line we may want to split `custom_widgets.py` into  more subparts but we can think about this when we see what ends up in it, and it's minor. I think this is a solid plan to proceed with!

**Comment by b-peri** [comment]
All good! Thanks Joe!

**Comment by JoeZiminski** [comment]
Hey @b-peri thanks for this! navigating after this refactor is very easy. FYI some cool github features, if in a PR you write `closes #<num>` where `<num>` is an issue number, it will link the PR to the issue and close it on merge which is handy (alterantively from the issue, on the right-hand panel you can go 'Development' and search the repo for a PR and link it that way). Cheers!
