### ISSUE TITLE
Use rclones `check` command to get a diff of changes.

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#263]
Hey @b-peri 

Rclone has a nice function [`check`](https://rclone.org/commands/rclone_check/) that returns a diff of local and remote files. I can wrap this within the datashuttle machinery and we can take a look at the output format.  I'll assign you as reviewer when it's done, cheers!

Note to self:  Rclone actually has as a reasonably recent [python-API](https://pypi.org/project/rclone-python/) so I'll try and use this, in generall all Rclone calls can go through this API. Actually, although it looks excellent it is not officially supported as far as I can tell, so will not use it.

**Comment by b-peri** [comment]
Hey @JoeZiminski, this sound perfect! Thanks a lot!
