### ISSUE TITLE
convenience functions 'get_latest_session, get_latest_subject'

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#27]
It would be convenient when setting up a new subject / session to quickly get the most research subject / session from remote, in case you forgot what session you are on. e.g.

project.get_latest_ses("sub-004")
> 'the latest session for sub-004 is: on remote: ses-010, on local: ses-002. Last push to remote was: xx-xx-xx'

(e.g. a case where setting up on a ephys computer where the last session was session 2, then 8 behavioural sessions have been run on a different computer and pushed to remote)

This could work by connecting to remote and checking metadata for most recent session.

**Comment by adamltyson** [comment]
Should we rely on remembering the session number? Could we query and then set up `session.next()`?

**Comment by JoeZiminski** [comment]
yes I'm not sure how to proceed with that, at one level it is very nice and convenient, but there are cases where it might be difficult and result in generating the wrong session:

 e.g. if a user is collecting data across 2 computers (local) and pushing to remote. For some reason the transfer to remote fails on one of the computers, and the next day from a different computer the next session is generated (the only available information to the local computer will me the local last session, and remote last session, but not the other local computer last session). There will then be some duplication across local computers. 

These kind of cases make me lean towards not auto-generating this ourselves, rather informing the user of the current status of the project 'as best we can tell' (i.e. most recent local session, most recent remote session) and make them make the final decision so they can't get mad at us.

**Comment by adamltyson** [comment]
> These kind of cases make me lean towards not auto-generating this ourselves, rather informing the user of the current status of the project 'as best we can tell' (i.e. most recent local session, most recent remote session) and make them make the final decision so they can't get mad at us.

Probably a good idea. I do think people will ask for a "next" function though. Could we have some confirmation:

```
Setting up next session....

Latest session pushed to remote is "010", on 2022-11-07, 17:35.

If this is not the last session, please ensure all data is synced to remote. Otherwise data may be corrupted.

Proceed with setting up session "011"? (y/n)
```

**Comment by JoeZiminski** [comment]
yes thats really nice, we can offer config to turn the warning on / off ('at your own peril'...)

**Comment by JoeZiminski** [comment]
1) query local, query remote for list of subject / session numbers
2) if any gaps (e.g. ses-001, ses-003) then throw a warning, this should never happen
3) suggest the next one, show message as Adam above.
