### ISSUE TITLE
`create_folders` should split returned paths by datatype

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#374]
Currently `create_folders` returns a big list of paths where datatypes are mixed.

It would be much better to split these by datatype, returning a dict of lists of paths `{"behav": [], "ephys": []}

[This function](https://github.com/neuroinformatics-unit/datashuttle/blob/aea2bb99dbe4a789e476e64b10cc9eae364a4da3/datashuttle/utils/folders.py#L67) needs to be changed.

**Comment by niksirbi** [comment]
Agreed, this makes sense.
