### ISSUE TITLE
Write a roadmap for datashuttle.

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#383]
It would be useful to write a roadmap on the website, to lay out the long term aims and plan for datashuttle.

**Comment by adamltyson** [comment]
It would also be useful to lay out somewhere (maybe here, on the NIU site) a roadmap for how/when tools will interoperate, e.g. spikewrap/movement/brainglobe being able to read/write to neuroblueprint.
