### ISSUE TITLE
`:html_theme.sidebar_secondary.remove:` displayed on the website 

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/datashuttle#392]
When building the docs on `main`, this is displayed at the top of index.html.

![datashuttle](https://github.com/neuroinformatics-unit/datashuttle/assets/13147259/9a973fda-bde5-4a9a-9c4b-5e9f2a11da43)

**Comment by JoeZiminski** [comment]
Hey @adamltyson that's strange, I just checked it works okay for me. Maybe a dependency issue? Worth trying a fresh env? I'm on `sphinx 7.1.2` and  `pydata-sphinx-theme 0.14.3`.

**Comment by adamltyson** [comment]
Yup, my env on this machine was v. old. Looks fine now.
