### ISSUE TITLE
Dependecy for conda install (show-in-file-manager) cannot be installed on MacOS in arm64 environment

### ISSUE THREAD

**Issue by NathanielH-snek** [neuroinformatics-unit/datashuttle#393]
**Describe the bug**
Basically if you try to install datashuttle from Conda you can't actually install show-in-file-manager. I think this is due to there not being an arm64 build on conda forge. You'll probably want to make this a dependecy from pip as it seems to work fine installing from pip.

**To Reproduce**
Run ```conda install -c conda-forge datashuttle```

**Expected behaviour**
datashuttle will install

**Log file**
N/A

**Screenshots**
N/A

**Computer used (please complete the following information):**

- OS: MacOS M1 Pro
- Version 14.5
- Hardware specs M1 Pro 16gb RAM

**Additional context**

**Comment by JoeZiminski** [comment]
Thanks for the bug report @NathanielH-snek! That's really useful, what we can do is:

1) Update the `show-in-file-manager` conda-forge to provide arm64 builds
2) Test the full conda install on the CI (at the moment RClone only is installed through conda). It would probably be good to test both full conda install as well as conda rclone + pip in the CI, but definitely full conda as first priority as that is the recommended way in the docs. It will also be good at this stage for us to check what backend CI is using, I think @niksirbi mentioned recently `macos-latest` is using silicon architecture.

Thanks again for raising this, don't hesitate to raise any other issues for problems / feedback you have as you use the package.

**Comment by niksirbi** [comment]
Yes, that is correct. The `macos-latest` runners now use silicon architecture. To test on "intel" Macs, you can use `macos-13`. See https://github.com/neuroinformatics-unit/movement/pull/170

**Comment by JoeZiminski** [comment]
`show-in-file-manager` is now out for `macos-arm` so this should now work in practice, #394 updates the tests

**Comment by JoeZiminski** [comment]
Thanks for raising this @NathanielH-snek, this has now been resolved by fixing the `show-in-file-manager` conda release and is properly tested in #394. It would be great to hear any feedback as you use the package so please don't hestitate to get in contact or open an issue anytime.
