### ISSUE TITLE
Module name doesn't match the repo name. 

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/datashuttle#4]
The module name is `manager` which is a) different to the repo name and b) already taken on PyPI. Possibly a good time to come up with a name for this project going forward? Off the top of my head - `datashuttle`? Open to suggestions.

**Comment by JoeZiminski** [comment]
I like datashuttle its snappy and nicely sums up the purpose. I've been thinking off and on about the name and didn't get very far. I'm happy to go with that, I agree now is a good time for the name change.

**Comment by niksirbi** [comment]
I like the `datashuttle` name. Can't think of anything catchier. Also requires no dashes/underscores, which is nice
