### ISSUE TITLE
Add automated Rclone copy at certain time of day

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#42]
A major benefit of datashuttle is setting automated upload from local PC to remote. Add this in before beta release

**Comment by JoeZiminski** [comment]
This will be harder than initially thought, all python-native solutions requiere the add to spin an event loop. Some possible solutions:

1) ask the user to keep the terminal open if scheduled updates are required. There would have to be an command like 'start schedule transfer' that they would have to start at the end of each day.  This would also require setting everything up again if the computer is shut down
2) use datashuttle command to call system("./scheduler.py") that will generate a new process running the script. Maybe this can return the process ID to allow to be killed later. However, I don't know how much about how this works in practice and across platforms, seems like it might cause antivirus issues / problems tracking these child processes down.
3) make a module that will use the systems native scheduler (e.g. cron, Windows Task Scheduler, macos Automater) (I can't find anything like it, I am suprised it does not already exist) . I feel like, if it is just pointing to a script and telling it when to run, it would not be that bad to implement as a separate repo (famous last words). There are already python API for interacting with cron, windows task scheduler

I think I prefer the third option as it uses native schedulers. This may cause some platform dependency issues however (though you'd hope these would all be stable across OS), but as this is non-critical feature it might be okay to not support this in some cases.

**Comment by JoeZiminski** [comment]
Hey @adamltyson, after talking to researchers most seem happy to manually send the data with a button press. As this will be significantly more difficult than anticipated and any user interested in this can run with cron jobs + the python API, do you think it is worth closing this? It could be reopened if there are many requests for it, but at present I think it will be a lot of work to make it cross platform and add relatively little.

**Comment by adamltyson** [comment]
Sounds good to me!
