### ISSUE TITLE
upload / download specific file is relative to rawdata rather than project dir

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#51]
When running `datashuttle test-project upload_project_dir_or_file rawdata/sub-03`, I got:
```bash
<3>ERROR : Local file system at /home/nsirmpilatze/Data/test-project/rawdata/rawdata/sub-03: error reading source root directory: directory not found
<3>ERROR : Attempt 1/3 failed with 1 errors and: directory not found
<3>ERROR : Local file system at /home/nsirmpilatze/Data/test-project/rawdata/rawdata/sub-03: error reading source root directory: directory not found
<3>ERROR : Attempt 2/3 failed with 1 errors and: directory not found
<3>ERROR : Local file system at /home/nsirmpilatze/Data/test-project/rawdata/rawdata/sub-03: error reading source root directory: directory not found
<3>ERROR : Attempt 3/3 failed with 1 errors and: directory not found
Failed to copy: directory not found
```
It looks as if the path is not read relative to the project directory, but instead relative to the `rawdata` folder. Is that behaviour desired? If yes, docstrings and cli help message should change accordingly.

**Comment by JoeZiminski** [comment]
Revisiting this, I am not sure of the best way to handle the top-level directories (e.g. rawdata, derivatives, analysis etc.). There are a number of ways this could be handled:

1) Make the user always input the top-level directory when performing any command. e.g. ```make_sub_dir("rawdata", "sub-001", "ses-001", data_type="all")```. This is the most clear, but for the most part we expect people to be using rawdata so this would be quite tiresome to always be adding this argument. 

2) Alternatively, have an option such as 'current_top_level_dir="rawdata"', then all commands assume this as the top-level dir. This is currently the way it is implemented. The downside of this is the user might forget what top-level dir they are on which could cause problems. It is also less intuitive. It is flexible, in that we could also have a setting `current_top_level_dir="all"` in which case "rawdata" and "derivatives" would be used. 

We could slightly adjust the convenience functions for uploading the entire project, currently `upload_all()` and `download_all()` to take an argument, with top-level directory e.g. `project.upload_all("rawdata")`, `project.upload_all("all")`, `project.upload_all(["derivatives", "raw_data"]). This would also be an easy way to implement moving an entire `code` or `analysis` folder. 

I think I prefer 2, although it is a little more confusing for the user. However, by the time they are going to be using anything but "rawdata", they presumably will have collected quite a lot of data with datashuttle and should be familiar enough with it. I think this could be stored with the rest of the configs, but with dedicated getter/setter functions. Thoughts @neuroinformatics-unit/neuroinformatics-team ?

**Comment by adamltyson** [comment]
I'm not sure what would be best, but I imagine that a lot of users will want a single function that just uploads everything. Rather than uploading specific datasets, can they just run one thing to ensure that everything is synced to the central store?

**Comment by niksirbi** [comment]
I also prefer 2, i.e. having a `current_top_level_dir` argument, with `rawdata`, `derivatives`, and `all` as options (defaulting to `rawdata`)

**Comment by lauraporta** [comment]
What about having the user giving as input the path to the "rawdata" dir once, store it somewhere and then use always that one unless they want to change it? In this way `upload()` and `download()` will always refer to the last specified path.
Similarly to how we define `remote origin` in git

**Comment by niksirbi** [comment]
I like Laura's idea, basically "use latest setting unless explicitly changed"

**Comment by JoeZiminski** [comment]
Agree this is nice, when they first load configs they can be asked to confirm they want to use "rawdata" (or change e.g. "derivaives") and then tell them the function they can use to change it in future

**Comment by JoeZiminski** [comment]
based on discussion:

- have background setting for raw data, derivatives, analysis or code "modes". Don't require specification on every call
- also provide "upload / download entire project" setting that will also copy anything in top level project dir
