### ISSUE TITLE
Profile tests and fix logging issue with tests

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#72]
1) some tests are running very slowly, this might be because of something during project setup, or more likely rclones checks. Possibly disable rlcone checks for tests, but will be good to log this incase they cause speed issues later
2) since logging was added, datashuttle logs capture by pytest are all printed at the end of testing, which is messy

**Comment by adamltyson** [comment]
@JoeZiminski dumb question - what are the "rclone checks"? Are these tests you've written or something as part of how rclone works?


> since logging was added, datashuttle logs capture by pytest are all printed at the end of testing, which is messy

This shouldn't happen, or at least I've not noticed it happen before with any of the other packages that use pytest & logging.

**Comment by JoeZiminski** [comment]
sorry this was not clear, these are the checksums and file-size checks that rlcone does to ensure transfer was sucessful. These can be skipped with `--ignore-checksum --ignore-size` if I understand correctly, but with a quick check they didn't seem to do much (I guess because at the moment I am transferring pretty much empty files). However, making just one rclone call sped things up a lot, it will be interesting to see if this translates to transferring larger files.

Yes I don't know what happened with the logging, I must have set something up a little funky!

**Comment by JoeZiminski** [comment]
There is also quite a lot of overhead in setting up / tearing down projects. This can almost certainly be optimised, also played with pytest fixture scope in test_ssh_file_transfer.py so setup and tear down only happens once per set of tests. However, most other tests rely on isolation with function scope, so will be a pain to back. On the deskstop tests are runnign quite fast, the only real bottleneck now is SSH tests.
