### ISSUE TITLE
Add more introductory documentation

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/datashuttle#93]
I left lots of comments about docs on https://github.com/neuroinformatics-unit/datashuttle/pull/68. I think generally the docs should be expanded and made more general. For `Get Started`, I would do something like:

  Introduction - all the basic info of why DataShuttle exists, what the main concepts are, and links to SWC-BluePrint so that the user can understand about projects etc
  Get Started - A basic walkthrough of either API/CLI to start transferring data
  Full Docs - All the information needed to use every feature
  API & CLI docs - as they are currently, a reference of specific functions/commands

**Comment by JoeZiminski** [comment]
addressed in #137. A second round of docs improvement is required, detailed in #191
