### ISSUE TITLE
[Feature] Use NUI unified method to make system calls

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/datashuttle#96]
here datashuttle calls system like 

[this](https://github.com/neuroinformatics-unit/datashuttle/blob/1f0718be24bbd9c44c817ceab23539d01f46f068/datashuttle/utils/rclone.py#L9)

but we recently discussed having NIU code for calling system based on BrainGlobe

relevant for swc_ephys too

**Comment by JoeZiminski** [comment]
I believe the [imlib](https://github.com/adamltyson/imlib/blob/625193be4a586d9040a48df9d51dbdd3a17c7d06/imlib/general/system.py#L258) implentation uses the older (<python 3.5) `subprocess` API (`subprocess.check_call`) as discussed [here])(https://stackoverflow.com/questions/40697583/whats-the-difference-between-pythons-subprocess-call-and-subprocess-run). In this case, the existing implementation should be okay as any failure during `subproecss.run` is returned to `stderr`. This is not true in the cause of `FileNotFound` error if the called program (in this case `rclone`) cannot be found, but this is handled explicitly [here](https://github.com/neuroinformatics-unit/datashuttle/blob/54888e3fd8e91c4dd6836cab6949b214e2c6b344/datashuttle/utils/rclone.py#L93). In this case I will close though I may have missed something.

**Comment by JoeZiminski** [comment]
@adamltyson does this sound okay?

**Comment by adamltyson** [comment]
Is the question "is it ok to stick with the existing implementation in datashuttle, and not adopt the imlib version"?

**Comment by JoeZiminski** [comment]
Yes that's the crux of it 😄 .

**Comment by adamltyson** [comment]
Yeah fine by me. It would be cool to add this stuff into an `niu-lib` package of some sort, but no reason to adopt the imlib version if it's out of date.
